kafkaUrl: &kafkaUrl ${KAFKA_BOOTSTRAP_SERVERS:kafka-1.dtm.local:9092}

kafka:
  adg:
    producer:
      property:
        bootstrap.servers: *kafkaUrl
    consumer:
      property:
        bootstrap.servers: *kafkaUrl
        group.id: adg-query-execution
    cluster:
      zookeeperHosts: ${ZOOKEEPER_HOSTS:kafka-1.dtm.local}
      rootPath: arenadata/cluster/21
    admin:
      adgUploadRq: "%s.%s.adg.upload.rq"
      adgUploadRs: "%s.%s.adg.upload.rs"
      adgUploadErr: "%s.%s.adg.upload.err"

tarantool:
  db:
    host: ${TARANTOOL_DB_HOST:10.92.3.21}
    port: ${TARANTOOL_DB_PORT:3311}
    user: ${TARANTOOL_DB_USER:admin}
    password: ${TARANTOOL_DB_PASS:cluster-cookie}
    operationTimeout: ${TARANTOOL_DB_OPER_TIMEOUT:60000}
  cartridge:
    url: ${TARANTOOL_CATRIDGE_URL:http://10.92.3.21:8811}

schema-registry:
  url: ${SCHEMA_REGISTRY_URL:http://10.92.3.21:8811}
