kafkaUrl: &kafkaUrl ${KAFKA_BOOTSTRAP_SERVERS:kafka-1.dtm.local:9092}

http:
  port: ${SERVER_PORT:8080}

env:
  name: ${DTM_NAME:local}

datasource:
  edml:
    sourceType: ${EDML_DATASOURCE:ADB}
    defaultChunkSize: ${EDML_DEFAULT_CHUNK_SIZE:1000}
    defaultMessageLimit: ${EDML_DEFAULT_MESSAGE_LIMIT:1000}
    pluginStatusCheckPeriodMs: ${EDML_STATUS_CHECK_PERIOD_MS:1000}
  service:
    options:
      database: ${SERVICEDB_DB_NAME:dtmservice_ilapa}
      user: ${SERVICEDB_USER:dtmuser}
      password: ${SERVICEDB_PASS:Cat6Gmt7Ncr}
      host: ${SERVICEDB_HOST:10.92.3.41}
      port: ${SERVICEDB_PORT:3306}
    poolOptions:
      maxSize: 5

kafka:
  producer:
    property:
      bootstrap.servers: *kafkaUrl
  consumer:
    adb:
      bootstrap.servers: *kafkaUrl
      group.id: adb-query-execution
    adg:
      bootstrap.servers: *kafkaUrl
      group.id: adg-query-execution
    adqm:
      bootstrap.servers: *kafkaUrl
      group.id: adqm-query-execution
  cluster:
    zookeeperHosts: ${ZOOKEEPER_HOSTS:kafka-1.dtm.local}
    rootPath: ${KAFKA_CLUSTER_ROOTPATH:arenadata/cluster/21}
  admin:
    inputStreamTimeoutMs: ${KAFKA_INPUT_STREAM_TIMEOUT_MS:1000}
    upload:
      requestTopic:
        adb: "%s.%s.adb.upload.rq"
        adg: "%s.%s.adg.upload.rq"
      responseTopic:
        adb: "%s.%s.adb.upload.rs"
        adg: "%s.%s.adg.upload.rs"
      errorTopic:
        adb: "%s.%s.adb.upload.err"
        adg: "%s.%s.adg.upload.err"

logging:
  level:
    ru.ibs.dtm.query.execution: ${WRITER_LOG_LEVEL:INFO}
