datasource:
  adb:
    options:
      database: ${ADB_DB_NAME:adb}
      user: ${ADB_USERNAME:gpadmin}
      password: ${ADB_PASS:gpadmin}
      host: ${ADB_HOST:10.92.3.14}
      port: ${ADB_PORT:5432}
      maxSize: 20

connector:
  adb:
    host: ${ADB_MPPR_CONNECTOR_HOST:10.92.3.14}
    port: ${ADB_MPPR_CONNECTOR_PORT:8086}
    url: ${ADB_MPPR_CONNECTOR_URL:/query}

