datasource:
  database: ${SERVICEDB_DB_NAME:dtmservice}
  user: ${SERVICEDB_USER:dtmuser}
  password: ${SERVICEDB_PASS:Cat6Gmt7Ncr}
  host: ${SERVICEDB_HOST:localhost}
  port: ${SERVICEDB_PORT:3306}
  maxPoolSize: 1

spring:
  liquibase:
    enabled: true

liquibase:
  command: ${LIQUIBASE_COMMAND:update}
  changeLog:
    serviceDb: classpath:db/changelog/serviceDb/changelog.yml
