version: '3.7'

networks:
  dtm-query-execution:

volumes:
  dtmservice:
  kafkalogs:

services:
  dtmservicedb:
    image: mariadb:10.5.3
    container_name: dtmservicedb
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - dtmservice:/var/lib/mysql
    environment:
      MYSQL_DATABASE: dtmservice
      MYSQL_USER: dtmuser
      MYSQL_PASSWORD: Cat6Gmt7Ncr
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"

  adb:
    image: postgres:10.4
    restart: always
    environment:
      POSTGRES_USER: gpadmin
      POSTGRES_PASSWORD:
      POSTGRES_DB: adb
    ports:
      - "5432:5432"

  zookeeper:
    image: zookeeper:3.6
    container_name: zk-1.dtm.local
    restart: always
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    container_name: kafka-1.dtm.local
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    volumes:
      - kafkalogs:/kafka
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1.dtm.local:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zk-1.dtm.local:2181
