version: '3.7'

services:
  dtm-query-execution-core:
    build:
      context: ..
      args:
        - DTM_JAR=./target/dtm-query-execution-core-2.4.0-SNAPSHOT.jar
    container_name: dtm-query-execution-core
    restart: always
    ports:
      - "8088:8088"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - ../config:/app/config:Z