version: '3.7'

services:
  dtm-query-execution-core:
    image: ${IMAGE}
    container_name: dtm-query-execution-core
    network_mode: bridge
    restart: always
    ports:
      - "8085:8080"
    environment:
      - SERVICEDB_DB_NAME=s_db_demo
      - SERVICEDB_USER=s_demo
      - SERVICEDB_PASS=Coin2Excels3Funder
      - SERVICEDB_HOST=database-1.dtm.local
      - SERVICEDB_PORT=3306
      - WRITER_LOG_LEVEL=TRACE
      - EDML_DATASOURCE=ADB
      - EDML_DEFAULT_CHUNK_SIZE=1000
      # For ADB plugin
      - KAFKA_BOOTSTRAP_SERVERS=kafka-3.dtm.local:9092
      - ADB_DB_NAME=adb_demo
      - ADB_USERNAME=demo
      - ADB_PASS=Usurer0Mold1Firmer
      - ADB_HOST=adbmaster-1.dtm.local
      - ZOOKEEPER_HOSTS=kafka-3.dtm.local
      - KAFKA_CLUSTER_ROOTPATH=arenadata/cluster/24
      - ADB_MPPR_CONNECTOR_HOST=demo-1.dtm.local
      - ADB_MPPR_CONNECTOR_PORT=8086
      # For ADG plugin
      - TARANTOOL_DB_HOST=tarantool-3.dtm.local
      - TARANTOOL_DB_PORT=3311
      - TARANTOOL_DB_USER=admin
      - TARANTOOL_DB_PASS=321
      - TARANTOOL_CATRIDGE_URL=http://tarantool-3.dtm.local:8811
      - SCHEMA_REGISTRY_URL=http://kafka-3.dtm.local:8081
