version: '3.7'

networks:
  dtm-query-execution:

volumes:
  dtmservice:
  kafkalogs:
  adqm-volume:
  adb-volume:

services:
  dtm-query-execution-core:
    build:
      context: ..
      args:
        - DTM_JAR=./target/dtm-query-execution-core-2.3.0-SNAPSHOT.jar
    container_name: dtm-query-execution-core
    restart: always
    networks:
      - dtm-query-execution
    depends_on:
      - dtmservicedb
      - zookeeper
      - kafka
      - adg
      - adqm
      - adb
    ports:
      - "8088:8088"
    environment:
      - SPRING_PROFILES_ACTIVE=local
    volumes:
      - ../config:/app/config:Z

  dtmservicedb:
    image: mariadb:10.5.3
    container_name: dtmservicedb
    restart: always
    networks:
      - dtm-query-execution
    ports:
      - "3306:3306"
    volumes:
      - dtmservice:/var/lib/mysql
    environment:
      MYSQL_DATABASE: dtmservice
      MYSQL_USER: dtmuser
      MYSQL_PASSWORD: Cat6Gmt7Ncr
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"

  zookeeper:
    image: zookeeper:3.6
    container_name: zk-1.dtm.local
    restart: always
    networks:
      - dtm-query-execution
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    container_name: kafka-1.dtm.local
    restart: always
    networks:
      - dtm-query-execution
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    volumes:
      - kafkalogs:/kafka
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1.dtm.local:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zk-1.dtm.local:2181

  adg:
    image: ci.arenadata.io/adg:0.5
    container_name: adg
    restart: always
    networks:
      - dtm-query-execution
    ports:
      - "8081:8081"

  adqm:
    image: yandex/clickhouse-server:20.4
    container_name: adqm
    restart: always
    networks:
      - dtm-query-execution
    depends_on:
      - kafka
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - adqm-volume:/var/lib/clickhouse
      - ./config/adqm/config.xml:/etc/clickhouse-server/config.xml:Z

  adb:
    image: postgres:12
    container_name: adb
    restart: always
    networks:
      - dtm-query-execution
    ports:
      - "5432:5432"
    volumes:
      - adb-volume:/var/lib/postgresql
    environment:
      POSTGRES_USER: gpadmin
      POSTGRES_PASSWORD: gpadmin
      POSTGRES_DB: adb
