datasource:
  adqm:
    database: ${ADQM_DB_NAME:upload}
    user: ${ADQM_USERNAME:}
    password: ${ADQM_PASS:}
    hosts: ${ADQM_HOSTS:10.92.3.24:8123}

ddl:
  cluster: ${ADQM_CLUSTER:test_arenadata}
  ttlSec: ${ADQM_TTL_SEC:3600}
  archiveDisk: ${ADQM_ARCHIVE_DISK:default}

mppw:
  consumerGroup: ${ADQM_CONSUMER_GROUP:adqm}
  kafkaBrokers: ${ADQM_BROKERS:10.92.3.31:9092}
  loadType: ${ADQM_MPPW_LOAD_TYPE:REST}
  restLoadUrl: ${ADQM_REST_LOAD_URL:http://10.92.3.3:8090/newdata}
  restLoadConsumerGroup: ${ADQM_REST_LOAD_GROUP:test_datamart.consumer}
